patreon: MouriNaruto
custom: [
  "https://paypal.me/MouriNaruto",
  "https://afdian.net/a/MouriNaruto",
  "https://github.com/MouriNaruto/MouriNaruto/tree/main/Sponsor#alipay",
  "https://github.com/MouriNaruto/MouriNaruto/tree/main/Sponsor#wechat"
]
