/*
 * PROJECT:   Mouri Internal Library Essentials
 * FILE:      Application.idl
 * PURPOSE:   Definition for the Mile.Xaml.Application
 *
 * LICENSE:   The MIT License
 *
 * DEVELOPER: Mouri_Naruto (Mouri_Naruto AT Outlook.com)
 */

namespace Mile.Xaml
{
    [default_interface]
    runtimeclass PlaceHolder
    {
        PlaceHolder();
    }
}
