/*
 * PROJECT:   Mouri Internal Library Essentials
 * FILE:      Application.idl
 * PURPOSE:   Definition for the Mile.Xaml.Application
 *
 * LICENSE:   The MIT License
 *
 * DEVELOPER: Mouri_Naruto (Mouri_Naruto AT Outlook.com)
 */

namespace Mile.Xaml
{
    interface IXamlMetadataContainer
    {
        Windows.Foundation.Collections.IVector<Windows.UI.Xaml.Markup.IXamlMetadataProvider> MetadataProviders { get; };
    };

    // Enable XamlHost transparency by using a undocumented API.
    // Reference: https://github.com/ADeltaX/IWindowPrivate/blob/main/IWindowPrivate.idl
    [uuid(06636C29-5A17-458D-8EA2-2422D997A922)]
    interface IWindowPrivate
    {
        Boolean TransparentBackground{ get; set; };
    }

    [default_interface]
    unsealed runtimeclass Application :
        Windows.UI.Xaml.Application,
        IXamlMetadataContainer,
        Windows.Foundation.IClosable
    {
        Application(Windows.Foundation.Collections.IVector<Windows.UI.Xaml.Markup.IXamlMetadataProvider> providers);
        protected Application();
        protected void Initialize();
    }

    [default_interface]
    runtimeclass XamlControlsResources : Windows.UI.Xaml.ResourceDictionary
    {
        XamlControlsResources();
    }
}
